# AntiFarmPlugin plugin configuration file.

# General settings.
settings:
  # Prefix to be used in messages to players.
  prefix: "&a[AntiFarmPlugin]&r "
  # Send plugin stats to bstats.
  bstats: true
  # Check for plugin updates.
  update-check: true
  # Break detected pistons for auto farm. ('true' option is recommended for performance.)
  break-pistons: true
  # Break detected blocks for auto farm. ('true' option is recommended for performance.)
  break-blocks: true
  # List of worlds you want to disable anti farm. (Case sensitive list.)
  disabled-worlds:
    - "SomeWorld"
    - "AnotherWorld"

# Anti afk fish farm settings.
anti-fishing:
  # Enable/Disable option.
  enable: true
  # Send warning message when player is blocked.
  warn: true
  # Warning message.
  warn-msg: "&cYou have reached the fishing limit in the same area, go to different areas to continue fishing!"
  # Get kicked off the server if the player keeps fishing.
  kick: false
  # Kicking message.
  kick-msg: "&cYou were kicked from the server due to afk fish farm!"
  # How many times can the player fish per chunk? (Fails do not count.)
  caught-fish-per-chunk: 10
  # Time to wait to fish again in the same chunk. (Default: 10 min = 600 seconds.)
  chunk-cooldown: 600

# Mob spawner settings.
mob-spawner-settings:
  # Prevent mob spawner from spawning creatures.
  prevent-spawn: false
  # Prevent players from breaking mob spawner. (Admins can still break it by sneak and hitting.)
  prevent-break: true
  # Preventing mob spawners from being converted by clicking with mob eggs.
  prevent-transformation: true
  # Warning message to player.
  player-warn-message: "&cYou can't break mob spawner, this action blocked on server!"
  # Warning message to admin.
  admin-warn-message: "&cMob spawner break is disabled on server. But you are an admin and if you want to break, you can. (Sneak + Attack)"
  # Transformation blocking message to admin.
  transformation-warn-message: "&cYou can't convert mob spawner, this action is blocked on server!"
  # Spawner data customization. (Spawner settings are in spawners.yml)
  spawner-data: false

# Villager settings.
villager-settings:
  # Once the villager gets a profession it prevents it from being changed.
  prevent-villagers-profession-change: true
  # Prevents villagers from harvesting and planting fields.
  prevent-villagers-harvesting-farms: true
  # Prevent villagers from breeding.
  prevent-villagers-breed: true
  # Prevents villagers from getting infected. (This blocks the way to get discounts from villagers on your server.)
  prevent-villagers-infection:
    # Enable/Disable option.
    enable: true
    # Chance of being infected. If this possibility is not realized, will die.
    # If set to 0, it will not be infected and die.
    # Even if the chance of infection is set to 100, there is always a risk of death.
    infection-percent: 30
  # Prevent zombie villagers from being cured. (This makes it difficult to reach villagers on your server, making them valuable.)
  prevent-zombie-villagers-cure:
    # Enable/Disable option.
    enable: true
    # Chance of being cured. If this possibility is not realized, will die.
    # If set to 0, it will not be cured and die.
    cure-percent: 30
  # Prevents villagers from being targeted by creatures. (Helps protect the villager population.)
  prevent-targeting-villager: false
  # Prevents trade with villagers.
  prevent-villager-trade: false
  # Prevents trade with wandering traders.
  prevent-wandering-trader-trade: false
  # Disables iron golem spawning with villager interaction.
  prevent-golem-spawning:
    # Prevents iron golem spawning when villager is scared or attacked.
    village-defense: false
    # Prevents iron golem spawning when the village is raiding.
    village-raids: false

# Automatic farms settings.
farms-settings:
  # Prevents farming by placing a block next to the cactus.
  prevent-cactus-farms: true
  # Prevents 'farm-blocks' from breaking and moving with piston.
  prevent-piston-farms: true
  # Prevents harvesting farm blocks using water.
  prevent-water-harvesting-farms: true
  # Prevents farm blocks from being taken by endermans.
  prevent-enderman-harvesting-farms: true
  # Prevents planting on a block of land that has not reached the full water level.
  prevent-waterless-farms: true
  # Prevents planting on farmland with light level below 8.
  prevent-lightless-farms: true
  # Prevents the snowman from leaving snow trail on the ground.
  prevent-snowball-farms: true
  # Prevents foxes from dropping sweet berries to the ground.
  prevent-berry-farms: true
  # Prevents 'farmland-blocks' with 'farm-blocks' from being moved by pistons.
  prevent-zerotick-farms: true
  # Prevents string dupe.
  prevent-string-dupe: true
  # Prevents dripstone farm.
  prevent-dripstone-farms: true
  # Prevents infinity lava with dripstone.
  prevent-infinity-lava: true

# If dispenser is looking at a farm block, it will be prevented from throwing items in the "blocked-item-list".
anti-dispenser:
  # Enable/Disable option.
  enable: true
  # Prevent shearing sheep with dispenser.
  prevent-dispenser-shearing: true
  # Blocked item list. (Case sensitive list.)
  blocked-item-list:
    - BONE_MEAL
    - GLASS_BOTTLE
    - WATER_BUCKET
    - LAVA_BUCKET

# Automatic mob farms settings.
prevent-mob-farms:
  # Enable/Disable option.
  enable: true
  # Allows drops from the creatures that die from special causes. (For custom entity killer plugins.)
  allow-custom-death-drops: false
  # Block experience drop from the creature the player didn't kill.
  block-drop-xp: true
  # Block item drop from the creature the player didn't kill.
  block-drop-item: true
  # Percentage of damage the player must inflict for the mob to loot.
  required-damage-percent-for-loot: 70
  # All afk mob farms are blocked by default.
  # If you only want to block only one creature's farm. Set 'blacklist' to 'true' and add the name of the creature you want to block to the 'moblist'.
  # If you only want to allow only one creature's farm. Set 'blacklist' to 'false' and add the name of the creature you want to block to the 'moblist'.
  # If you want all afk creature farms to be blocked don't touch the default settings.
  blacklist: false
  # blacklist: true -> 'moblist' is blacklist.
  # blacklist: false -> 'moblist' is whitelist.
  # When adding mobs to the list, all letters should be capitalized. (Case sensitive list.)
  moblist:
    - BAT

# Raid farms settings.
prevent-raid-farms:
  # Enable/Disable option.
  enable: true
  # Cooldown between raids. (Seconds.)
  cooldown: 600

# Creature item output limit. Production range in which mobs must be fed.
# When frogs reach maximum froglight production number, they should be fed with smile ball to continue producing.
# When chickens reach maximum egg production number, they should be fed with wheat seeds to continue producing.
# When the cows are milked, they should be fed with wheat and a cooling period should be waited for milking again.
# The maximum production number is determined by a random number between the maximum and minimum specified in the configuration.
# The maximum production number is different per mob and varies with each feeding.
# The minimum should not be greater than the maximum.
creature-product-limiter:
  frog:
    enable: true
    froglight-min: 5
    froglight-max: 10
    feed-msg: "&aFrog successfully fed."
  chicken:
    enable: true
    egg-min: 5
    egg-max: 10
    feed-msg: "&aChicken successfully fed."
  cow:
    enable: true
    milk-cooldown-sec: 600
    milk-msg: "&aCow successfully milked."
    feed-msg: "&aCow successfully fed."
    cooldown-msg: "&cThis cow can be milked again after &f%time% &cseconds."
    malnutrition-warning-msg: "&cMilking is unsuccessful because the cow is malnourished."

# List of blocks on which any farm block can be grown.
farmland-blocks:
  - GRASS_BLOCK
  - DIRT
  - COARSE_DIRT
  - ROOTED_DIRT
  - SAND
  - RED_SAND
  - FARMLAND
  - SOUL_SAND
  - END_STONE
  - STONE

# List of all things that can be farmed.
farm-blocks:
  - CACTUS
  - SUGAR_CANE
  - SUGAR_CANE_BLOCK
  - REEDS
  - BAMBOO
  - MELON
  - MELON_STEM
  - MELON_BLOCK
  - ATTACHED_MELON_STEM
  - PUMPKIN
  - PUMPKIN_STEM
  - ATTACHED_PUMKIN_STEM
  - WHEAT
  - CROPS
  - CARROT
  - CARROTS
  - POTATO
  - POTATOES
  - BEETROOT
  - BEETROOTS
  - BEETROOT_BLOCK
  - SWEET_BERRY_BUSH
  - COCOA
  - CAVE_VINES
  - CAVE_VINES_PLANT
  - NETHER_WART
  - CHORUS_PLANT
  - CHORUS_FLOWER
  - RED_MUSHROOM
  - BROWN_MUSHROOM
  - CRIMSON_FUNGUS
  - WARPED_FUNGUS
  - MOSS_BLOCK
  - KELP
  - BEE_NEST
  - BEEHIVE
  - SUNFLOWER
  - LILAC
  - ROSE_BUSH
  - PEONY
  - WEEPING_VINES
  - WEEPING_VINES_PLANT
  - TWISTING_VINES
  - TWISTING_VINES_PLANT
  - BIG_DRIPLEAF
  - AMETHYST_CLUSTER
  - DRIPSTONE_BLOCK
  - POINTED_DRIPSTONE
  - MANGROVE_LEAVES
